// src/app/counter/Counter.tsx
import * as React from 'react'
import { ReactToCustomElement } from 'src/react/ReactToCE'

export let Counter: React.ComponentType<{
  count: number
  onChange(next: number): void
}> = props => {
  const { count, onChange } = props
  return (
    <>
      <button onClick={() => onChange(count - 1)}>-1</button>
      <span>Current count: {count}</span>
      <button onClick={() => onChange(count + 1)}>+1</button>
    </>
  )
}
Counter.displayName = 'app-counter-ui'
ReactToCustomElement(Counter)

// src/app/counter/counter.component.ts
import { Component, OnInit } from '@angular/core'
import { Counter } from './Counter'
import { useReact } from 'src/react/ReactToCE'

@Component({
    selector: 'app-counter',
    template: useReact(Counter, CounterComponent)
})
export class CounterComponent implements OnInit, ReactComponentProps<typeof Counter> {
    count = 0
    onChange(newCount: number) {
        this.count = newCount
    }

    ngOnInit() {}
}

<app-counter-ui [count]="count" (onChange)="onChange($event)"></app-counter-ui>
